name: Deploy to staging

on:
  push:
    branches: 
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Example output creation"
      id: "my_step"
      run: |
        profile= "${{ secrets.STAGINGPUBLISHPROFILE }}"
        echo "Output [$profile]"
    - name: "Deploy"
      uses: UKHSA-Internal/webhook-action@v1.0.0
      with:
        url: ${{ secrets.STAGINGPUBLISHPROFILE }}
        data: >
          {"command": "publish"}
